kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2

metadata:
  name: prod-app-two-hpa
  namespace: prod-app-ns

spec:
  scaleTargetRef:
    kind: Deployment
    name: app-two-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
