kind: Service
apiVersion: v1

metadata:
  name: app-two-svc
  namespace: prod-app-ns

spec:
  selector:
    app: prod-app-two
  ports:
    - port : 3001
      targetPort: 3001
      protocol : TCP
  type : ClusterIP
